s=StateManager("192.168.1.126", 9600)
print("opening the device")
s.open()
time.sleep(5)
print("turn off the device")
s.turn_off()
time.sleep(5)
print("turn on the device")
s.turn_on()
time.sleep(5)
print("set the device speed off")
s.set_speed(SPEED_OFF)
time.sleep(5)
print("set the device speed low")
s.set_speed(SPEED_LOW)
time.sleep(5)
print("set the device speed medium")
s.set_speed(SPEED_MEDIUM)
time.sleep(5)
print("set the device speed high")
s.set_speed(SPEED_HIGH)
time.sleep(5)
print("set the device mode timing")
s.set_mode(MODE_TIMING)
time.sleep(5)
print("set the device mode auto")
s.set_mode(MODE_AUTO)
time.sleep(5)
print("set the device mode manually")
s.set_mode(MODE_MANUALLY)
time.sleep(5)
print("closing the device")
s.close()
print("waitting for end")
time.sleep(5)